### ISSUE TITLE
Naming conflict with yet another YAT

### ISSUE THREAD

**Issue by maettu-this** [Jewest/YAT#52]
Hi Jeffrey,

Just came across your YAT by accident. I am the author of yet another [YAT](https://sourceforge.net/projects/y-a-terminal/), started in 2003 and public since 2007. Funny, back then, a naming conflict happend as well as, as Dieter Fauth's [Yat3](http://dieter-fauth.bplaced.net/tools/Yat3/Yat3.html) came around about the same time.

I assume you have never come across my YAT and were not aware of this naming conflict, so I decided to create this ticket. Seeing your YAT is "younger" and less wide-spread, you might consider giving it a different name, as people might confuse it with my YAT. If you don't, that's fine with me. After all, "yet another" just asks for more than one ;-)

And of course, feel free to try out my YAT. It has been downloaded around 200'000 times since 2007 and proven quite useful in very many use cases. It is yet limited to Windows though, but then it might cover your cases as well. If not, let me know.

Best regards,
Matthias

**Comment by Jewest** [comment]
fixed with the merge, changing the Yat#
